### PR TITLE
You are far too kind Yuriy

### PR DESCRIPTION
**Pull request by mytchel**
But really. Don't run even as a standard user.
Damn lucky media comes after /home and backup's of /home were on /media.
I should really think things through before I do stupid shit.

### CODE REVIEW

**Comment by yackermann** [comment]
Sweet. Merging.

**Comment by yackermann** [comment]
@mytch444 got tox?

**Comment by mytchel** [comment]
Nope. What client should I use?

**Comment by yackermann** [comment]
qtox or utox (they are fucking the same.)

2015-03-31 0:37 GMT+13:00 Mytchel notifications@github.com:

**Comment by yackermann** [comment]
@mytch444 https://wiki.tox.im/Binaries

**Comment by mytchel** [comment]
B-b-but "Pissing off kiddies since 1337 B.C." if I use Ratox I can join the 1337 group...
-- give me a couple minutes. I'll see what I can get working.

**Comment by mytch444** [comment]
Okay, got utox should I email you my id?

**Comment by yackermann** [comment]
jep

2015-03-31 1:05 GMT+13:00, Mytchel notifications@github.com:

**Pull request merged**
